package com.jayasree.contactfinder;

public class Datas {
     static void initializeDb(DbHelper dbHelper) {
        dbHelper.insertContact("Ernad", "", "", "0483 2766121", "8547615800", "tlkerd@kerala.nic.in");
        dbHelper.insertContact("Nilambur", "", "", "0493 1221471", "8547615900", "tlknbr@kerala.nic.in");
        dbHelper.insertContact("Ponnani", "", "", "0494 2666038", "8547615400", "tlkpni@kerala.nic.in");
        dbHelper.insertContact("Kondotty", "", "", "0483 2713311", "8547618450", "kondottytaluk@gmail.com");
        dbHelper.insertContact("Tirur", "", "", "0494 2422238", "8547617446", "tlktir@kerala.nic.in");
        dbHelper.insertContact("Perinthalmanna", "", "", "0493 3227230", "8547617445", "tlkptm@kerala.nic.in");
        dbHelper.insertContact("Tirurangadi", "", "", "0494 2461055", "8547615600", "tlktdi@kerala.nic.in");
        dbHelper.insertContact("Ernad", "Anakkayam", "Village office, Anakkayam, Anakkayam.P.O., - 676 509", "", "8547615819", "vo-anakkayam.rev@kerala.gov.in");
        dbHelper.insertContact("Ernad", "Areacode", "Village office, Areacode, Areacode.P.O.,- 673 639", "", "8547615813", "vo-areacode.rev@kerala.gov.in");
        dbHelper.insertContact("Ernad", "Chembrasseri", "Village office, Chembrasseri, Chembrasseri.P.O., 676 521", "", "8547615815", "vo-chembrasseri.rev@kerala.gov.in");
        dbHelper.insertContact("Ernad", "Edavanna", "Village office, Edavanna,Edavanna.P.O.- 676 541", "", "8547615807", "vo-edavanna.rev@kerala.gov.in");
        dbHelper.insertContact("Ernad", "Elankur", "Village office, Elankur, Elankur.P.O., 676 122", "", "8547615812", "vo-elankur.rev@kerala.gov.in");
        dbHelper.insertContact("Ernad", "Karakunnu", "Village office, Karakunnu,Karakunnu.P.O.- 676 123", "", "8547615806", "vo-karakunnu.rev@kerala.gov.in");
        dbHelper.insertContact("Ernad", "Kavanur", "Village office,Kavanur, Kavanur.P.O., 673 639", "", "8547615808", "vo-kavanur.rev@kerala.gov.in");
        dbHelper.insertContact("Ernad", "Kizhuparamba", "Village office, Kizhuparamba, Kizhuparamba.P.O - 673 639", "", "8547615828", "vo-kizhuparamba.rev@kerala.gov.in");
        dbHelper.insertContact("Ernad", "Malappuram", "Village office, Malappuram, Down Hill.P.O.- 676505", "", "8547615816", "vo-mpm.rev@kerala.gov.in");
        dbHelper.insertContact("Ernad", "Manjeri", "Village office, Manjeri,Manjeri.P.O.- 676 121", "", "8547615802", "vo-manjeri.rev@kerala.gov.in");
        dbHelper.insertContact("Ernad", "Melmuri", "Village office, Melmuri, Melmuri.P.O., 676517", "", "8547615817", "vo-melmuri.erd.rev@kerala.gov.in");
        dbHelper.insertContact("Ernad", "Narukara", "Village office, Narukara, Narukara.P.O, 676 122", "", "8547615804", "vo-narukara.rev@kerala.gov.in");
        dbHelper.insertContact("Ernad", "Panakkad", "Village office, Panakkad, Pattarkadavu.P.O., 676519", "", "8547615823", "vo-panakkad.rev@kerala.gov.in");
        dbHelper.insertContact("Ernad", "Pandallur", "Village office, Pandallur, Kadambode.P.O., - 676 521", "", "8547615820", "vo-pandallur.rev@kerala.gov.in");
        dbHelper.insertContact("Ernad", "Pandikkad", "Village office, Pandikkad, Pandikkad.P.O., - 676 521", "", "8547615814", "vo-pandikkad.rev@kerala.gov.in");
        dbHelper.insertContact("Ernad", "Payyanad", "Village office, Payyanad, Payyanad, P.O.- 676 122", "", "8547615803", "vo-payyanad.rev@kerala.gov.in");
        dbHelper.insertContact("Ernad", "Perakamanna", "Village office, Perakamanna, Pannippara.P.O.- 676 541", "", "8547615811", "vo-perakamanna.rev@kerala.gov.in");
        dbHelper.insertContact("Ernad", "Pookkottur", "Village office, Pookkottur, Valluvambram.P.O.,- 673 642", "", "8547615818", "vo-pookkottur.rev@kerala.gov.in");
        dbHelper.insertContact("Ernad", "Pulpatta", "Village office, Pulpatta, Pulpatta.P.O, - 676 123", "", "8547615809", "vo-pulpatta.rev@kerala.gov.in");
        dbHelper.insertContact("Ernad", "Trikkalangode", "Village office, Trikkalangode,Trikkalangode.P.O., 676 123", "", "8547615805", "vo-trikkalangode.rev@kerala.gov.in");
        dbHelper.insertContact("Ernad", "Urangattiri", "Village office, Urangattiri., Urangattiri.P.O - 673639", "", "8547615827", "vo-urangattiri.rev@kerala.gov.in");
        dbHelper.insertContact("Ernad", "Vettikattiri", "Village office, Vettikattiri, Pandikkad.P.O., - 676 521", "", "8547615810", "vo-vettikattiri.rev@kerala.gov.in");
        dbHelper.insertContact("Ernad", "Vettilappara", "Village office, Vettilappara, Vettilappara.P.O., - 673 639", "", "8547615834", "vo-vettilappara.rev@kerala.gov.in");
        dbHelper.insertContact("Perinthalmanna", "Aliparamba", "Village office, Aliparamba, Aliparamba-P.O. - 679357", "", "8547615713", "vo-aliparamba.rev@kerala.gov.in");
        dbHelper.insertContact("Perinthalmanna", "Anamangad", "Village office, Anamangad, Anamangad.P.O.- 679357", "", "8547615714", "vo-anamangad.rev@kerala.gov.in");
        dbHelper.insertContact("Perinthalmanna", "Angadippuram", "Village office, Angadippuram, Angadippuram.P.O., PIN .679321", "", "8547615715", "vo-angadippuram.rev@kerala.gov.in");
        dbHelper.insertContact("Perinthalmanna", "Arakkuparamba", "Village office, Arakkuparamba,Arakkuparamba .P.O., 679322", "", "8547615705", "vo-arakkuparamba.rev@kerala.gov.in");
        dbHelper.insertContact("Perinthalmanna", "Edappatta", "Village office, Edappatta, Edappatta.P.O., -679326", "", "8547615711", "vo-edappatta.rev@kerala.gov.in");
        dbHelper.insertContact("Perinthalmanna", "Elamkulam", "Village office, Elamkulam, Kunnakkavu.P.O., - 679340", "", "8547615712", "vo-elamkulam.rev@kerala.gov.in");
        dbHelper.insertContact("Perinthalmanna", "Karyavattam", "Village office, Karyavattam, Mannarmala.P.O.,- 679325", "", "8547615710", "vo-karyavattam.rev@kerala.gov.in");
        dbHelper.insertContact("Perinthalmanna", "Keezhattur", "Village office, Keezhattur, Pattikkad.P.O., - 679325", "", "8547615707", "vo-keezhattur.rev@kerala.gov.in");
        dbHelper.insertContact("Perinthalmanna", "Kodur", "Village office, Kodur, Kodur.P.O.- 676504", "", "8547615719", "vo-kodur.rev@kerala.gov.in");
        dbHelper.insertContact("Perinthalmanna", "Koottilangadi", "Village office, Koottilangadi, Padinhattumuri.P.O., - 676506", "", "8547615722", "vo-koottilangadi.rev@kerala.gov.in");
        dbHelper.insertContact("Perinthalmanna", "Kuruva", "Village office, Kuruva, Vattallur.P.O., - 676507", "", "8547615724", "vo-kuruva.rev@kerala.gov.in");
        dbHelper.insertContact("Perinthalmanna", "Kuruvambalam", "Village office, Kuruvambalam, Kuruvambalam.P.O., - 679338", "", "8547615721", "vo-kuruvambalam.rev@kerala.gov.in");
        dbHelper.insertContact("Perinthalmanna", "Mankada", "Village office, Mankada, Kadannamanna.P.O., 679324", "", "8547615718", "vo-mankada.rev@kerala.gov.in");
        dbHelper.insertContact("Perinthalmanna", "Melattur", "Village office, Melattur, Melattur.P.O., 679326", "", "8547615704", "vo-melattur.rev@kerala.gov.in");
        dbHelper.insertContact("Perinthalmanna", "Moorkkanad", "Village office, Moorkkanad, Kolathur.P.O., - 679338", "", "8547615723", "vo-moorkkanad.rev@kerala.gov.in");
        dbHelper.insertContact("Perinthalmanna", "Nenmini", "Village office, Nenmini,Tachinaganadam P.O., PIN.679325", "", "8547615708", "vo-nenmini.rev@kerala.gov.in");
        dbHelper.insertContact("Perinthalmanna", "Pathaikara", "Village office, Pathaikara,Eravimangalam .P.O., - 679340", "", "8547615703", "vo-pathaikara.rev@kerala.gov.in");
        dbHelper.insertContact("Perinthalmanna", "Perinthalmanna", "Village office, Perinthalmanna, Perinthalmanna P O,- 679322", "", "8547615702", "vo-perinthalmanna.rev@kerala.gov.in");
        dbHelper.insertContact("Perinthalmanna", "Pulamanthole", "Village office, Pulamanthole, Pulamanthole.P.O.,- 679323", "", "8547615720", "vo-pulamanthole.rev@kerala.gov.in");
        dbHelper.insertContact("Perinthalmanna", "Puzhakkattiri", "Village office, Puzhakkattiri, Puzhakkattiri.P.O., - 679321", "", "8547615725", "vo-puzhakkattiri.rev@kerala.gov.in");
        dbHelper.insertContact("Perinthalmanna", "Thazhekkode", "Village office, Thazhekkode, Thazhekkode West.P.O., - 679322", "", "8547615706", "vo-thazhekkode.rev@kerala.gov.in");
        dbHelper.insertContact("Perinthalmanna", "Vadakkanagara", "Village office, Vadakkanagara,Makkaraparamba.P.O.- 676507", "", "8547615717", "vo-vadakkanagara.rev@kerala.gov.in");
        dbHelper.insertContact("Perinthalmanna", "Valambur", "Village office, Valambur, Tirurkkad.P.O., PIN .679321", "", "8547615716", "vo-valambur.rev@kerala.gov.in");
        dbHelper.insertContact("Perinthalmanna", "Vettathur", "Village office, Vettathur, Vettathur.P.O., 679325", "", "8547615709", "vo-vettathur.rev@kerala.gov.in");
        dbHelper.insertContact("Ponnani", "Alamkode", "Village office,Alamkode, Nannamukku.P.O., - 679575", "", "8547615411", "vo-alamkode.rev@kerala.gov.in");
        dbHelper.insertContact("Ponnani", "Edappal", "Village office, Edappal,Edappal.P.O., -679576", "", "8547615404", "vo-edappal.rev@kerala.gov.in");
        dbHelper.insertContact("Ponnani", "Ezhuvathiruthy", "Village office, Ezhuvathiruthy, Eshwaramanagalam.P.O., -679573", "", "8547615403", "vo-ezhuvathiruthy.rev@kerala.gov.in");
        dbHelper.insertContact("Ponnani", "Kalady", "Village office, Kalady, Kadanchery.P.O., - 679582", "", "8547615406", "vo-kalady.rev@kerala.gov.in");
        dbHelper.insertContact("Ponnani", "Maranchery", "Village office, Maranchery,Maranchery.P.O., - 679581", "", "8547615408", "vo-maranchery.rev@kerala.gov.in");
        dbHelper.insertContact("Ponnani", "Nannamukku", "Village office, Nannamukku, Mookkuthala.P.O, - 679574", "", "8547615412", "vo-nannamukku.rev@kerala.gov.in");
        dbHelper.insertContact("Ponnani", "Perumpadappa", "Village office, Perumpadappa, Perumpadappa.P.O., -679580", "", "8547615410", "vo-perumpadappa.rev@kerala.gov.in");
        dbHelper.insertContact("Ponnani", "Ponnani Nagaram", "Village office, Ponnani Nagaram, Ponnani Nagaram.P.O, - 679583", "", "8547615402", "vo-ponnaninagaram.rev@kerala.gov.in");
        dbHelper.insertContact("Ponnani", "Tavanur", "Village office, Tavanur, Tavanur.P.O., -679573", "", "8547615407", "vo-tavanur.rev@kerala.gov.in");
        dbHelper.insertContact("Ponnani", "Vattamkulam", "Village office, Vattamkulam, Vattamkulam.P.O., -679578", "", "8547615405", "vo-vattamkulam.rev@kerala.gov.in");
        dbHelper.insertContact("Ponnani", "Veliyancode", "Village office, Veliyancode, Gramam.P.O., -679579", "", "8547615409", "vo-veliyancode.rev@kerala.gov.in");
        dbHelper.insertContact("Nilambur", "Akampadam", "Village office, Akampadam, Eranhimangad.P.O., 679329", "", "8547615904", "vo-akampadam.rev@kerala.gov.in");
        dbHelper.insertContact("Nilambur", "Amarambalam", "Village office, Amarambalam, Amarambalam.P.O., - 679332", "", "8547615908", "vo-amarambalam.rev@kerala.gov.in");
        dbHelper.insertContact("Nilambur", "Chokkad", "Village office, Chokkad, Chokkad.P.O, - 679355", "", "8547615902", "vo-chokkad.rev@kerala.gov.in");
        dbHelper.insertContact("Nilambur", "Chungathara", "Village office, Chungathara, , Chungathara.P.O., 679334", "", "8547615911", "vo-chungathara.rev@kerala.gov.in");
        dbHelper.insertContact("Nilambur", "Edakkara", "Village office, Edakkara, Edakkara.P.O., 679331", "", "8547615910", "vo-edakkara.rev@kerala.gov.in");
        dbHelper.insertContact("Nilambur", "Kalikavu", "Village office, Kalikavu, Kalikavu.P.O., - 676525", "", "8547615919", "vo-kalikavu.rev@kerala.gov.in");
        dbHelper.insertContact("Nilambur", "Karulai", "Village office, Karulai, Karulai.P.O., 679330", "", "8547615903", "vo-karulai.rev@kerala.gov.in");
        dbHelper.insertContact("Nilambur", "Karuvarakundu", "Village office, Karuvarakundu, Karuvarakundu.P.O., Punnakkad- 676523", "", "8547615912", "vo-karuvarakundu.rev@kerala.gov.in");
        dbHelper.insertContact("Nilambur", "Kerala Estate", "Village office, Kerala Estate,Kerala Estate.P.O., -676525", "", "8547615907", "vo-keralaestate.rev@kerala.gov.in");
        dbHelper.insertContact("Nilambur", "Kurumbalangode", "Village office, Kurumbalangode, Eramamunda.P.O., - 679334", "", "8547615906", "vo-kurumbalangode.rev@kerala.gov.in");
        dbHelper.insertContact("Nilambur", "Mampad", "Village office, Mampad, Vadapuram.P.O., 676542", "", "8547615913", "vo-mampad.rev@kerala.gov.in");
        dbHelper.insertContact("Nilambur", "Moothedam", "Village office, Moothedam", "", "", "");
        dbHelper.insertContact("Nilambur", "Nilambur", "Village office, Nilambur, Nilambur.P.O., - 679329", "", "8547615909", "vo-nilambur.rev@kerala.gov.in");
        dbHelper.insertContact("Nilambur", "Porur", "Village office, Porur, Chatahangottupuram.P.O, Cherikodi - 679328", "", "8547615915", "vo-porur.rev@kerala.gov.in");
        dbHelper.insertContact("Nilambur", "Pothukallu", "Village office, Potukallu", "", "", "");
        dbHelper.insertContact("Nilambur", "Pullippadam", "Village office, Pullippadam, Mampad.P.O., -676542", "", "8547615914", "vo-pullippadam.rev@kerala.gov.in");
        dbHelper.insertContact("Nilambur", "Thiruvali", "Village office, Thiruvali, Thiruvali.P.O., - 676123", "", "8547615920", "vo-thiruvali.rev@kerala.gov.in");
        dbHelper.insertContact("Nilambur", "Tuvvur", "Village office, Tuvvur, Tuvvur.P.O., - 679327", "", "8547615916", "vo-tuvvur.rev@kerala.gov.in");
        dbHelper.insertContact("Nilambur", "Vazhikkadavu", "Village office, Vazhikkadavu, Manimooly.P.O., - 679333", "", "8547615905", "vo-vazhikkadavu.rev@kerala.gov.in");
        dbHelper.insertContact("Nilambur", "Vellayur", "Village office, Vellayur, Anchachavidi.P.O., - 676512", "", "8547615918", "vo-vellayur.rev@kerala.gov.in");
        dbHelper.insertContact("Nilambur", "Wandur", "Village office, Wandur, Wandur.P.O., - 679328", "", "8547615917", "vo-wandur.rev@kerala.gov.in");
        dbHelper.insertContact("Tirurangadi", "A.R.Nagar", "Village office, A.R.Nagar, A.R.Nagar.P.O., - 676305", "", "8547615616", "vo-arnagar.rev@kerala.gov.in");
        dbHelper.insertContact("Tirurangadi", "Ariyallur", "Village office, Ariyallur, Ariyallur.P.O., - 676312", "", "8547615605", "vo-ariyallur.rev@kerala.gov.in");
        dbHelper.insertContact("Tirurangadi", "Edarikode", "Village office, Edarikode", "", "", "");
        dbHelper.insertContact("Tirurangadi", "Moonniyur", "Village office, Moonniyur, Moonniyur.P.O., - 676313", "", "8547615607", "vo-moonniyur.rev@kerala.gov.in");
        dbHelper.insertContact("Tirurangadi", "Kannamangalam", "Village office, Kannamangalam, Cherur.P.O., - 676314", "", "8547615615", "vo-kannamangalam.rev@kerala.gov.in");
        dbHelper.insertContact("Tirurangadi", "Nannambra", "Village office, Nannambra, Theyyalungal.P.O., - 676320", "", "8547615619", "vo-nannambra.rev@kerala.gov.in");
        dbHelper.insertContact("Tirurangadi", "Neduva", "Village office, Neduva, Parappanangadi.P.O., - 676303", "", "8547615610", "vo-neduva.rev@kerala.gov.in");
        dbHelper.insertContact("Tirurangadi", "Oorakam", "Village office, Oorakam, Oorakam Keezhmuri.P.O., - 676519", "", "8547615611", "vo-oorakam.rev@kerala.gov.in");
        dbHelper.insertContact("Tirurangadi", "Othukkungal", "Village office, Othukkungal, Othukkungal.P.O., - 676528", "", "8547615614", "vo-othukkungal.rev@kerala.gov.in");
        dbHelper.insertContact("Tirurangadi", "Parappanangadi", "Village office, Parappanangadi, Parappanangadi.P.O., - 676303", "", "8547615602", "vo-parappanangadi.rev@kerala.gov.in");
        dbHelper.insertContact("Tirurangadi", "Parappur", "Village office, Parappur, ParappurP.O., - 676503", "", "8547615617", "vo-parappur.rev@kerala.gov.in");
        dbHelper.insertContact("Tirurangadi", "Peruvallur", "Village office, Peruvallur, Parambilpeedika.P.O., - 676317", "", "8547615618", "vo-peruvallur.rev@kerala.gov.in");
        dbHelper.insertContact("Tirurangadi", "Thenhippalam", "Village office, Thenhippalam, Thenhippalam.P.O., - 673636", "", "8547615606", "vo-thenhippalam.rev@kerala.gov.in");
        dbHelper.insertContact("Tirurangadi", "Thennala", "Village office, Thennala, Valakkulam.P.O., - 676508", "", "8547615612", "vo-thennala.rev@kerala.gov.in");
        dbHelper.insertContact("Tirurangadi", "Tiruranagdi", "Village office, Tiruranagdi, Tiruranagdi.P.O., 676306", "", "8547615603", "vo-tiruranagdi.rev@kerala.gov.in");
        dbHelper.insertContact("Tirurangadi", "Vallikunnu", "Village office, Vallikunnu, Vallikunnu.P.O., - 673314", "", "8547615604", "vo-vallikunnu.rev@kerala.gov.in");
        dbHelper.insertContact("Tirurangadi", "Vengara", "Village office,Vengara, Vengara.P.O., - 676304", "", "8547615613", "vo-vengara.rev@kerala.gov.in");
        dbHelper.insertContact("Tirur", "Ananthavoor", "Village office, Ananthavoor, Ananthavoor.P.O.,- 676301", "", "8547615509", "vo-ananthavoor.rev@kerala.gov.in");
        dbHelper.insertContact("Tirur", "Athavanad", "Village office, Athavanad, Athavanad.P.O., - 676301", "", "8547615523", "vo-athavanad.rev@kerala.gov.in");
        dbHelper.insertContact("Tirur", "Cheriyamundam", "Village office, Cheriyamundam, Banglamkunnu., Cheriyamundam .P.O., - 676106", "", "8547615515", "vo-cheriyamundam.rev@kerala.gov.in");
        dbHelper.insertContact("Tirur", "Edayur", "Village office, Edayur, Vayanasala Junction, Edayur North.P.O., - 676552", "", "8547615525", "vo-edayur.rev@kerala.gov.in");
        dbHelper.insertContact("Tirur", "Irimbiliyam", "Village office, Irimbiliyam, Valiyakunnu.P.O., - 676552", "", "8547615526", "vo-irimbiliyam.rev@kerala.gov.in");
        dbHelper.insertContact("Tirur", "Kalpakancheri", "Village office, Kalpakanchery, Kalpakanchery.P.O., - 676551", "", "8547615517", "vo-kalpakancheri.rev@kerala.gov.in");
        dbHelper.insertContact("Tirur", "Kattiparuthi", "Village office, Kattiparuthi, Valancheri Town, Valancheri.P.O., - 676552", "", "8547615524", "vo-kattiparuthi.rev@kerala.gov.in");
        dbHelper.insertContact("Tirur", "Kottakkal", "Village office, Kottakkal, Arayvaidyasala Road, Kottakkal.P.O., - 676503", "", "8547615521", "vo-kottakkal.rev@kerala.gov.in");
        dbHelper.insertContact("Tirur", "Kurumbathur", "Village office, Kurumbathur, Kurumbathur.P.O., 676301", "", "8547615528", "vo-kurumbathur.rev@kerala.gov.in");
        dbHelper.insertContact("Tirur", "Kuttippuram", "Village office, Kuttippuram, Kuttippuram.P.O., - 679571", "", "8547615530", "vo-kuttippuram.rev@kerala.gov.in");
        dbHelper.insertContact("Tirur", "Mangalam", "Village office,Mangalam, Mangalam P O 676561", "", "8547615505", "vo-mangalam.rev@kerala.gov.in");
        dbHelper.insertContact("Tirur", "Marakkara", "Village office, Marakkara, Marakkara.P.O., - 676553", "", "8547615529", "vo-marakkara.rev@kerala.gov.in");
        dbHelper.insertContact("Tirur", "Melmuri", "Village office, Melmuri, Kadampuzha.P.O., 676553", "", "8547615527", "vo-melmuri.tir.rev@kerala.gov.in");
        dbHelper.insertContact("Tirur", "Naduvattom", "Village office, Naduvattom, Pazhoor.P.O., - 679567", "", "8547615531", "vo-naduvattom.rev@kerala.gov.in");
        dbHelper.insertContact("Tirur", "Niramaruthur", "Village office, Niramaruthur, Chakkaramoola, Niramaruthur.P.O., - 676109", "", "8547615519", "vo-niramaruthur.rev@kerala.gov.in");
        dbHelper.insertContact("Tirur", "Ozhur", "Village office, Ozhur, Pulparamba, Ozhur.P.O., - 676307", "", "8547615513", "vo-ozhur.rev@kerala.gov.in");
        dbHelper.insertContact("Tirur", "Pariyapuram", "Village office, Pariyapuram, Pariyapuram.P.O., - 676302", "", "8547615520", "vo-pariyapuram.rev@kerala.gov.in");
        dbHelper.insertContact("Tirur", "Perumanna", "Village office, Perumanna, Kuttippala. P.O., - 676501", "", "8547615518", "vo-perumanna.rev@kerala.gov.in");
        dbHelper.insertContact("Tirur", "Ponmala", "Village office, Ponmala, Chappanangadi.P.O., - 676528", "", "8547615522", "vo-ponmala.rev@kerala.gov.in");
        dbHelper.insertContact("Tirur", "Ponmundam", "Village office, Ponmundam, Cheriyamundam .P.O., - 676106", "", "8547615514", "vo-ponmundam.rev@kerala.gov.in");
        dbHelper.insertContact("Tirur", "Purathur", "Village office, Purathur, Kavilakkad, Purathur.P.O., - 676102", "", "8547615507", "vo-purathur.rev@kerala.gov.in");
        dbHelper.insertContact("Tirur", "Tanalur", "Village office, Tanalur, Tanalur.P.O., - 676307", "", "8547615511", "vo-tanalur.rev@kerala.gov.in");
        dbHelper.insertContact("Tirur", "Tanur", "Village office, Tanur, Near Railway Station, Tanur.P.O., - 676302", "", "8547615512", "vo-tanur.rev@kerala.gov.in");
        dbHelper.insertContact("Tirur", "Thalakkad", "Village office, Thalakkad, Vengaloor.P.O., - 676102", "", "8547615503", "vo-thalakkad.rev@kerala.gov.in");
        dbHelper.insertContact("Tirur", "Thirunavaya", "Village office, Thirunavaya, Kunnumpuram., Thirunavaya.P.O., - 676301", "", "8547615508", "vo-thirunavaya.rev@kerala.gov.in");
        dbHelper.insertContact("Tirur", "Tirur", "Village office, Tirur, Tirur P.O., - 676101", "", "8547615502", "vo-tirur.rev@kerala.gov.in");
        dbHelper.insertContact("Tirur", "Trikkandiyur", "Village office, Trikkandiyur, Tirur.P.O., 676101", "", "8547615510", "vo-trikkandiyur.rev@kerala.gov.in");
        dbHelper.insertContact("Tirur", "Triprangode", "Village office, Triprangode, Alathiyur.P.O., - 676102", "", "8547615504", "vo-triprangode.rev@kerala.gov.in");
        dbHelper.insertContact("Tirur", "Valavannur", "Village office, Valavannur, Kadungathukundu, Kalpakanchery.P.O., - 676551", "", "8547615516", "vo-valavannur.rev@kerala.gov.in");
        dbHelper.insertContact("Tirur", "Vettom", "Village office, Vettom, Alissery, Vettom.P.O., - 676102", "", "8547615506", "vo-vettom.rev@kerala.gov.in");
        dbHelper.insertContact("Kondotty", "Cheekode", "Village office, Cheekode, Omanoor.P.O- 673645", "", "8547615830", "vo-cheekode.rev@kerala.gov.in");
        dbHelper.insertContact("Kondotty", "Chelembra", "Village office, Chelembra, Chelembra.P.O.., -673634", "", "8547615609", "vo-chelembra.rev@kerala.gov.in");
        dbHelper.insertContact("Kondotty", "Cherukavu", "Village office, Cherukavu, Pulikkal.P.O.- 673 367", "", "8547615832", "vo-cherukavu.rev@kerala.gov.in");
        dbHelper.insertContact("Kondotty", "Kondotty", "Village office, Kondotty, Kondotty.P.O.-676 638", "", "8547615824", "vo-kondotty.rev@kerala.gov.in");
        dbHelper.insertContact("Kondotty", "Kuzhimanna", "Village office, Kuzhimanna, Kuzhimanna.P.O., - 673641", "", "8547615825", "vo-kuzhimanna.rev@kerala.gov.in");
        dbHelper.insertContact("Kondotty", "Morayur", "Village office, Morayur, Morayur.P.O, -673642", "", "8547615822", "vo-morayur.rev@kerala.gov.in");
        dbHelper.insertContact("Kondotty", "Muthuvallur", "Village office, Muthuvallur, Thavanur.P.O., - 673 368", "", "8547615831", "vo-muthuvallur.rev@kerala.gov.in");
        dbHelper.insertContact("Kondotty", "Nediyiruppu", "Village office, Nediyiruppu,Nediyiruppu.P.O., 673 638", "", "8547615821", "vo-nediyiruppu.rev@kerala.gov.in");
        dbHelper.insertContact("Kondotty", "Pallikkal", "Village office, Pallikkal,Pallikkal. P.O., - 673634", "", "8547615608", "vo-pallikkal.rev@kerala.gov.in");
        dbHelper.insertContact("Kondotty", "Pulikkal", "Village office, Pulikkal, Pulikkal.P.O.- 673 637", "", "8547615826", "vo-pulikkal.rev@kerala.gov.in");
        dbHelper.insertContact("Kondotty", "Vazhakkad", "Village office, Vazhakkad, Cheruvayur.P.O.,- 673 645", "", "8547615829", "vo-vazhakkad.rev@kerala.gov.in");
        dbHelper.insertContact("Kondotty", "Vazhayoor", "Village office, Vazhayoor, Vazhayoor.P.O.- 673 633", "", "8547615833", "vo-vazhayoor.rev@kerala.gov.in");
    }
}
